using BuildingBlocks.Constants;
using BuildingBlocks.EFCore;
using BuildingBlocks.Enums;
using BuildingBlocks.Logging;
using BuildingBlocks.Middlewares;
using FluentPOS.Identity.API.Data;
using FluentPOS.Identity.API.Extensions;

var builder = WebApplication.CreateBuilder(args);
builder.AddCommonLoging(builder.Environment);
builder.Services.AddAuthorization();
builder.Services.AddSingleton<ExceptionMiddleware>();
builder.Services.AddEFCoreDbContext<IdentityContext>(builder.Configuration, Database.PostgreSQL, ConnectionStrings.DefaultConnection);
builder.Services.AddScoped<IDataSeeder, IdentityDataSeeder>();
builder.Services.AddIdentityServer(builder.Environment);
var app = builder.Build();
app.UseEFCoreMigration<IdentityContext>(builder.Environment);
app.UseMiddleware<ExceptionMiddleware>();
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.UseIdentityServer();
app.Run();
