using BuildingBlocks.Constants;
using BuildingBlocks.EFCore;
using BuildingBlocks.Enums;
using BuildingBlocks.Logging;
using BuildingBlocks.Middlewares;
using BuildingBlocks.Options;
using BuildingBlocks.Web;
using FluentPOS.Identity.API.Data;
using FluentPOS.Identity.API.Extensions;

var builder = WebApplication.CreateBuilder(args);
var appConfig = builder.Services.GetRequiredConfiguration<AppConfig>();
builder.RegisterSerilog(builder.Environment, appConfig.Name);
builder.Services.AddAuthorization();
builder.Services.AddSingleton<ExceptionMiddleware>();
builder.Services.RegisterContext<IdentityContext>(builder.Configuration, Database.PostgreSQL, ConnectionStrings.DefaultConnection);
builder.Services.AddScoped<IDataSeeder, IdentityDataSeeder>();
builder.Services.AddIdentityServer(builder.Environment);
var app = builder.Build();
app.ConfigureMigrations<IdentityContext>(builder.Environment);
app.UseMiddleware<ExceptionMiddleware>();
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.UseIdentityServer();
app.Run();
